/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.awt.Color;
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Register() {
        initComponents();
        
        
    }
      /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        aadharno = new javax.swing.JTextField();
        phno = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        signup = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 100, -1));

        username.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 100, -1));

        aadharno.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        getContentPane().add(aadharno, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 100, -1));

        phno.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        getContentPane().add(phno, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 100, -1));

        password.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 100, 20));

        signup.setBackground(new java.awt.Color(153, 153, 153));
        signup.setFont(new java.awt.Font("Sitka Subheading", 0, 14)); // NOI18N
        signup.setText("Sign-up");
        signup.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        signup.setDoubleBuffered(true);
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        getContentPane().add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("have one?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 450, 110, -1));

        jLabel2.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 480, 60, -1));

        cancel.setBackground(new java.awt.Color(153, 153, 153));
        cancel.setFont(new java.awt.Font("Sitka Subheading", 0, 14)); // NOI18N
        cancel.setText("Cancel");
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, -1, -1));

        label.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\White Minimalist Travel Vlog Youtube Intro (1).gif")); // NOI18N
        getContentPane().add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 620));

        setSize(new java.awt.Dimension(1084, 607));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
     int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

    if (response == JOptionPane.YES_OPTION) {
        System.exit(0);
    }
    }//GEN-LAST:event_cancelMouseClicked

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
     if (name.getText().isEmpty() || username.getText().isEmpty() || password.getText().isEmpty()|| aadharno.getText().isEmpty() || phno.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please fill in all fields", "Error", JOptionPane.ERROR_MESSAGE);
        return; 
    }   
     else {
        // Additional validation for Aadhar and phone number
        String aadharNumber = aadharno.getText();
        String phoneNumber = phno.getText();

        if (aadharNumber.length() != 12 || !aadharNumber.matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "Aadhar number must contain exactly 12 digits.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (phoneNumber.length() != 10 || !phoneNumber.matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "Phone number must contain exactly 10 digits.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
     }
    try {
    String url = "jdbc:mysql://localhost:3306/javapro";
    String user = "root";
    String pass = "0000";
    Connection con = DriverManager.getConnection(url, user, pass);

   
    String checkUserQuery = "SELECT COUNT(*) FROM users WHERE username = ?";
    PreparedStatement checkUserPst = con.prepareStatement(checkUserQuery);
    checkUserPst.setString(1, username.getText());

    ResultSet rs = checkUserPst.executeQuery();
    rs.next();
    int count = rs.getInt(1);

    if (count == 0) {
        
        String insertQuery = "INSERT INTO users (name,username, password,mobilenumber,aadharnumber) VALUES (?,?,?,?,?)";
        PreparedStatement insertPst = con.prepareStatement(insertQuery);
        insertPst.setString(2, username.getText());
        insertPst.setString(3, password.getText());
        insertPst.setString(1,name.getText());
        insertPst.setString(4,aadharno.getText());
        insertPst.setString(5,phno.getText());
        int rowsAffected = insertPst.executeUpdate();

        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(null, "ACCOUNT CREATED SUCESSFULLY");
            new login().setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "ACCOUNT CREATION FAILES");
        }
    } else {
        // Username already exists, show a message or take appropriate action
        JOptionPane.showMessageDialog(null, "Username already exists");
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(null, e);
} 
     


    }//GEN-LAST:event_signupActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
          new login().setVisible(true);
          this.setVisible(false);
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Register registerWindow = new Register();
        registerWindow.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aadharno;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel label;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField phno;
    private javax.swing.JButton signup;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
