/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;
public class viewtodo extends javax.swing.JFrame {

    /**
     * Creates new form viewtodo
     */
    private String user;
    public viewtodo(String username) {
        this.user=username;
        initComponents();
        fetchData();
    }
    private void fetchData() {
    try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/javapro", "root", "0000")) {
        // Fetch charge IDs from customerstripdetails table
        String chargeIdsQuery = "SELECT accommodationchargeid, transportchargeid, foodchargeid, shoppingchargeid, activitieschargeid, entertainmentchargeid FROM customerstripdetails WHERE customerid = ?";
        try (PreparedStatement chargeIdsStatement = conn.prepareStatement(chargeIdsQuery)) {
            chargeIdsStatement.setString(1, user);

            try (ResultSet chargeIdsResultSet = chargeIdsStatement.executeQuery()) {
                if (chargeIdsResultSet.next()) {
                    String accommodationChargeId = chargeIdsResultSet.getString("accommodationchargeid");
                    String transportChargeId = chargeIdsResultSet.getString("transportchargeid");
                    String foodChargeId = chargeIdsResultSet.getString("foodchargeid");
                    String shoppingChargeId = chargeIdsResultSet.getString("shoppingchargeid");
                    String activitiesChargeId = chargeIdsResultSet.getString("activitieschargeid");
                    String entertainmentChargeId = chargeIdsResultSet.getString("entertainmentchargeid");

                    // Now fetch descriptions for each charge ID and set the text for the corresponding text fields
                    accomodation.setText(fetchDescription(conn, "accommodationcharge", accommodationChargeId));
                    transport.setText(fetchDescription(conn, "transportcharge", transportChargeId));
                    food.setText(fetchDescription(conn, "foodcharge", foodChargeId));
                    shopping.setText(fetchDescription(conn, "shoppingexpence", shoppingChargeId,"shoppingchargeid"));
                    activities.setText(fetchDescription(conn, "activitiescharge", activitiesChargeId));
                    entertainment.setText(fetchDescription(conn, "entertainmentexpence", entertainmentChargeId,"entertainmentchargeid"));
                }
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
}

private String fetchDescription(Connection conn, String tableName, String chargeId) throws SQLException {
    String descriptionQuery = "SELECT description FROM " + tableName + " WHERE " + tableName + "id = ?";
    try (PreparedStatement descriptionStatement = conn.prepareStatement(descriptionQuery)) {
        descriptionStatement.setString(1, chargeId);

        try (ResultSet descriptionResultSet = descriptionStatement.executeQuery()) {
            return descriptionResultSet.next() ? descriptionResultSet.getString("description") : "";
        }
    }
}
private String fetchDescription(Connection conn, String tableName, String chargeId,String id) throws SQLException {
    String descriptionQuery = "SELECT description FROM " + tableName + " WHERE " + id + " = ?";
    try (PreparedStatement descriptionStatement = conn.prepareStatement(descriptionQuery)) {
        descriptionStatement.setString(1, chargeId);

        try (ResultSet descriptionResultSet = descriptionStatement.executeQuery()) {
            return descriptionResultSet.next() ? descriptionResultSet.getString("description") : "";
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        accomodation = new javax.swing.JTextField();
        transport = new javax.swing.JTextField();
        food = new javax.swing.JTextField();
        shopping = new javax.swing.JTextField();
        activities = new javax.swing.JTextField();
        entertainment = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

       
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Subheading", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Accomodation");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Sitka Subheading", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tansport");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Sitka Subheading", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("food");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Sitka Subheading", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Shopping");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("Sitka Subheading", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("activites");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

        jLabel6.setFont(new java.awt.Font("Sitka Subheading", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Entertainment");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, -1, -1));

        jButton1.setText("Back");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 560, -1, -1));
        getContentPane().add(accomodation, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 360, 40));
        getContentPane().add(transport, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 360, 40));
        getContentPane().add(food, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 360, 40));

        shopping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shoppingActionPerformed(evt);
            }
        });
        getContentPane().add(shopping, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 290, 360, 40));

        activities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                activitiesActionPerformed(evt);
            }
        });
        getContentPane().add(activities, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 360, 40));

        entertainment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entertainmentActionPerformed(evt);
            }
        });
        getContentPane().add(entertainment, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, 360, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\WhatsApp Image 2023-12-07 at 00.27.01.jpeg")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 650));

        setSize(new java.awt.Dimension(1084, 649));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void shoppingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shoppingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shoppingActionPerformed

    private void entertainmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entertainmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entertainmentActionPerformed

    private void activitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_activitiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_activitiesActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       this.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accomodation;
    private javax.swing.JTextField activities;
    private javax.swing.JTextField entertainment;
    private javax.swing.JTextField food;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField shopping;
    private javax.swing.JTextField transport;
    // End of variables declaration//GEN-END:variables
}
